# _BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  DEPTH_ON: False
  REFINE_ON: False
  PLANE_ON: False
  AXIS_ON: True
  META_ARCHITECTURE: "PlaneRCNN"
  FREEZE: ['backbone', 'proposal_generator', 'roi_heads.box_head', 'roi_heads.box_predictor']
  WEIGHTS: "exps/step1_bbox/model_0008999.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "PlaneRCNNROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 2
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 1000000
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 16
DATASETS:
  TRAIN: ("arti_train",)
  TEST: ("arti_val",)
TEST:
  EVAL_PERIOD: 1000
  SAVE_VIS: False
  EVAL_GT_BOX: False
DATALOADER:
  NUM_WORKERS: 4
VIS_PERIOD: 5000
OUTPUT_DIR: "exps/step2_axis"